---
kind: pipeline
type: docker
name: check-drone
steps:
  - name: build
    image: rust:1.65
    commands:
      - cargo build --release
  
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github
      files: /drone/src/*
      checksum:
        - sha512

trigger:
    event:
      - tag
