---
kind: pipeline
type: docker
name: check-drone
steps:
  - name: build
    image: rust:1.65
    commands:
      # - cargo build --release --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu
      - cargo build --release 
  
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github
      files: /drone/src/target/release/check
      # checksum:
      #   - sha512

trigger:
  # branch: 
    # - main
    event:
      - tag
