---
kind: pipeline
type: docker
name: check-drone
steps:
  
  - name: test
    image: rust:1.65
    commands:
      - cargo test
    settings:
      when:
        branch: main 
  
  - name: build
    image: rust:1.65
    commands:
      # - cargo build --release --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu
      - cargo build --release 
    when:
        event:
          - tag
  
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github
      files: /drone/src/target/release/check
      checksum:
        - sha512
    when:
        event:
          - tag 

# trigger:
#   # branch: 
#     # - main
#     event:
#       - tag
